spring:
    profiles:
        active: dev # by default, the active file is "dev". during production, it is replaced to "prod" due to Azure's environment variables

api:
    endpoint:
        base-url: /api/v1
server:
    port: 80